server:
  port: 8080

logging:
  level:
    com.itlike: debug
  path: "C:/log/SpringMVC.log"

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    templates-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.itlike.pojo


